// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://edneuvbxnunndntuiouj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVkbmV1dmJ4bnVubmRudHVpb3VqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwODA2NjQsImV4cCI6MjA2MzY1NjY2NH0.8fh5_iqZDO52X3JWZyQFfHQljkwSJvl7rYaKKY2wLgM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);